# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a num-arr12. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform num-arr12 multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
import numpy as np

In [4]:
### Assignment 1: Array Creation and Manipulation

### 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

num_arr1 = np.random.randint(1, 21, size=(5, 5))

num_arr1[:, 2] = 1

num_arr1

array([[ 1,  7,  1, 16, 18],
       [ 8,  1,  1, 19,  5],
       [11, 16,  1,  4, 12],
       [ 2,  9,  1,  4, 20],
       [ 8, 11,  1,  6, 12]], dtype=int32)

In [7]:
### 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

num_arr2 = np.arange(1, 17).reshape(4, 4)

np.fill_diagonal(num_arr2, 0)

num_arr2

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

In [12]:
### Assignment 2: Array Indexing and Slicing

### 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

num_arr3 = np.arange(1, 37).reshape(6, 6)

print(num_arr3)

print(num_arr3[2:5, 1:4])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [18]:
### 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

num_arr4 = np.random.randint(0, 100, size=(5, 5))

print(num_arr4)

print(np.concatenate([num_arr4[0, :], num_arr4[-1, :], num_arr4[1:-1, 0], num_arr4[1:-1, -1]]))

[[39 50  8 15 42]
 [69 67 75 35  1]
 [83 11 51 52 10]
 [84 74 43  0  6]
 [54 37 21 85 93]]
[39 50  8 15 42 54 37 21 85 93 69 83 84  1 10  6]


In [20]:
### Assignment 3: Array Operations

### 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

num_arr5 = np.random.randint(0, 100, size=(3, 4))
print(num_arr5)

num_arr6 = np.random.randint(0, 100, size=(3, 4))
print(num_arr6)

print("Addition : ", num_arr5+num_arr6)
print("Subtraction : ", num_arr5-num_arr6)
print("Multiplication : ", num_arr5*num_arr6)
print("Division : ", num_arr5/num_arr6)

[[18 30 93 35]
 [35 42 65 46]
 [86 93 14 56]]
[[42  2 68 16]
 [ 4 95  3 98]
 [ 9 77 29 90]]
Addition :  [[ 60  32 161  51]
 [ 39 137  68 144]
 [ 95 170  43 146]]
Subtraction :  [[-24  28  25  19]
 [ 31 -53  62 -52]
 [ 77  16 -15 -34]]
Multiplication :  [[ 756   60 6324  560]
 [ 140 3990  195 4508]
 [ 774 7161  406 5040]]
Division :  [[ 0.42857143 15.          1.36764706  2.1875    ]
 [ 8.75        0.44210526 21.66666667  0.46938776]
 [ 9.55555556  1.20779221  0.48275862  0.62222222]]


In [25]:
### 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

num_arr7 = np.arange(1, 17).reshape(4, 4)
print(num_arr7)

row_sum = np.sum(num_arr7, axis=1)
print(row_sum)

column_sum = np.sum(num_arr7, axis=0)
print(column_sum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[10 26 42 58]
[28 32 36 40]


In [28]:
### Assignment 4: Statistical Operations

### 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

num_arr8 = np.random.randint(0, 100, size=(5, 5))
print(num_arr8)

print(np.mean(num_arr8))
print(np.median(num_arr8))
print(np.std(num_arr8))
print(np.var(num_arr8))

[[69 58 53  2 22]
 [40 77 52 24 58]
 [79 37 37 63 58]
 [41 74 54 12 25]
 [54 83 81 95 69]]
52.68
54.0
23.256345370672495
540.8575999999999


In [31]:
### 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

num_arr9 = np.arange(1, 10).reshape(3, 3)
print(num_arr9)

mean_arr9 = np.mean(num_arr9)
std_dev_arr9 = np.std(num_arr9)

normalize_arr9 = (num_arr9 - mean_arr9) / std_dev_arr9
print(normalize_arr9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [32]:
### Assignment 5: Broadcasting

### 1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

num_arr10 = np.random.randint(0, 100, size=(3, 3))

num_arr10_1d = np.random.randint(0, 100, size=(3, ))

result = num_arr10 + num_arr10_1d

print(num_arr10)
print(num_arr10_1d)
print(result)

[[63 83  1]
 [53  6 49]
 [64 63 26]]
[71 69 57]
[[134 152  58]
 [124  75 106]
 [135 132  83]]


In [35]:
### 2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

num_arr11 = np.random.randint(0, 100, size=(4, 4))

num_arr11_1d = np.random.randint(0, 100, size=(4, ))

result = num_arr11 - num_arr11_1d.reshape(-1, 1)

print(num_arr11,"\n")
print(num_arr11_1d, "\n")
print(result)

[[82 36 19 44]
 [35 71 73 14]
 [18  5 32 31]
 [ 3  9 29 14]] 

[96 82 90 11] 

[[-14 -60 -77 -52]
 [-47 -11  -9 -68]
 [-72 -85 -58 -59]
 [ -8  -2  18   3]]


In [38]:
### Assignment 6: Linear Algebra

### 1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

num_arr12 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

determinant = np.linalg.det(num_arr12)

try: 
    inverse = np.linalg.inv(num_arr12) 
except np.linalg.LinAlgError: 
    inverse = "Matrix is singular and cannot be inverted."

eigenvalues = np.linalg.eigvals(num_arr12)

print("Matrix:\n", num_arr12) 
print("\nDeterminant:", determinant) 
print("\nInverse:\n", inverse) 
print("\nEigenvalues:", eigenvalues)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant: 0.0

Inverse:
 Matrix is singular and cannot be inverted.

Eigenvalues: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


In [39]:
### 2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

num_arr13 = np.random.randint(0, 100, size=(2, 3))
num_arr14 = np.random.randint(0, 100, size=(3, 2))

result = np.dot(num_arr13, num_arr14)

print(num_arr13,"\n")
print(num_arr14,"\n")
print(result,"\n")

[[29 18 57]
 [79 52 63]] 

[[64 53]
 [41 75]
 [41 56]] 

[[ 4931  6079]
 [ 9771 11615]] 



In [44]:
### Assignment 7: Advanced Array Manipulation

### 1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

num_arr15 = np.arange(1, 10).reshape(3, 3)
print(num_arr15)

num_arr15 = num_arr15.reshape(1, 9)
print(num_arr15)

num_arr15 = num_arr15.reshape(9, 1)
print(num_arr15)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [45]:
### 2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

num_arr16 = np.random.randint(0, 100, size=(5, 5))
print(num_arr16)

num_arr16_flat = num_arr16.flatten()
print(num_arr16_flat)

num_arr16_reflat = num_arr16_flat.reshape(5, 5)
print(num_arr16_reflat)

[[59 92 40 30 88]
 [50 71 62 63 56]
 [76 64 28 88 10]
 [49 29 65 63 56]
 [14 29 99 17  0]]
[59 92 40 30 88 50 71 62 63 56 76 64 28 88 10 49 29 65 63 56 14 29 99 17
  0]
[[59 92 40 30 88]
 [50 71 62 63 56]
 [76 64 28 88 10]
 [49 29 65 63 56]
 [14 29 99 17  0]]


In [46]:
### Assignment 8: Fancy Indexing and Boolean Indexing

### 1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

num_arr17 = np.random.randint(0, 100, size=(5, 5))

num_arr17_corners = num_arr17[[0, 0, -1, -1], [0, -1, 0, -1]]

print(num_arr17,"\n")
print(num_arr17_corners,"\n")

[[62 85 24 77 52]
 [62 34 53  3 54]
 [ 6 60  9 13  2]
 [86 44 61 11  3]
 [27 56 29 82 56]] 

[62 52 27 56] 



In [47]:
### 2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

num_arr18 = np.random.randint(0, 100, size=(4, 4))

print(num_arr18)

num_arr18[num_arr18 > 10] = 10

print(num_arr18)

[[36 73 38  9]
 [84 57 43 16]
 [83  7 91 56]
 [60 86  1 13]]
[[10 10 10  9]
 [10 10 10 10]
 [10  7 10 10]
 [10 10  1 10]]


In [48]:
### Assignment 9: Structured Arrays

### 1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

data_type = [('Name', 'U10'), ('Age', 'i4'), ('Weight', 'f4')]

num_arr19 = np.array([('Alice', 25, 55.0),
                      ('Bob', 30, 85.5),
                      ('Charlie', 20, 72.3)], dtype=data_type)

print(num_arr19)

num_arr19_sorted = np.sort(num_arr19, order='Age')

print(num_arr19_sorted)

[('Alice', 25, 55. ) ('Bob', 30, 85.5) ('Charlie', 20, 72.3)]
[('Charlie', 20, 72.3) ('Alice', 25, 55. ) ('Bob', 30, 85.5)]
